name: Cypress Tests
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run run:regression
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        if: always()
        with:
          name: cypress-execution-report
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Automation
          SLACK_TITLE: Test Results
          SLACK_MESSAGE: "Test Automation Report :rocket:\n\nHi Team,\n\nThe automation report is now available, and you can access it in both video and report formats for a comprehensive overview of the test results. 📊✨\nYou can view the report here: https://github.com/OrenOfficial/Cypress-Automation-Regression-Suite/actions/runs/${{github.run_id}} \nFeel free to check it out"
          SLACK_COLOR: ${{ job.status }}
          
